name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"

jobs:
  Linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
      - uses: pre-commit/action@v3.0.1

  Test:
    needs: Linting
    name: ${{ matrix.os }}, ${{ matrix.env }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os: [ubuntu-latest]
        env:
          - ci/envs/311-minimal.yaml
          - ci/envs/311-no-optional-deps.yaml
          - ci/envs/311-latest.yaml
          - ci/envs/312-latest.yaml
          - ci/envs/313-latest.yaml
          - ci/envs/314-latest.yaml

        include:
          - env: ci/envs/314-latest.yaml
            os: macos-latest
          - env: ci/envs/314-latest.yaml
            os: windows-latest
          - env: ci/envs/314-dev.yaml
            os: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v3
        with:
          environment-file: ${{ matrix.env }}

      - name: Install package
        # install without deps to avoid installing default but optional pyproj/pyogrio
        run: pip install -e . --no-deps

      - name: Check and Log Environment
        run: |
          python -V
          python -c "import geopandas; geopandas.show_versions();"
          micromamba info
          micromamba list

      - name: Test
        run: |
          pytest -v -r a --color=yes --cov=dask_geopandas --cov-append --cov-report term-missing --cov-report xml .

      - uses: codecov/codecov-action@v7
